from . import CustomBaseException

class TaskArgsValidationError(CustomBaseException):
    pass
